'use client';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { createClient } from '@/lib/supabase';
import type { FriendHistorySummary } from '@/lib/friend-history';

export interface FriendInsightsProps { friendId: string; friendTag: string; friendName: string; }
export default function FriendInsights({ friendId, friendTag, friendName }: FriendInsightsProps) {
  const router = useRouter(); const [summary, setSummary] = useState<FriendHistorySummary | null>(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [shared, setShared] = useState(''); const [shareId, setShareId] = useState('');
  const request = async (refresh = false) => { const supabase = createClient(); const { data: { session } } = await supabase.auth.getSession(); if (!session) throw new Error('Sign in required'); const response = await fetch(refresh ? '/api/friend-decks' : `/api/friend-decks?friendId=${encodeURIComponent(friendId)}`, { method: refresh ? 'POST' : 'GET', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${session.access_token}` }, ...(refresh ? { body: JSON.stringify({ friendId }) } : {}) }); if (!response.ok) throw new Error(); const data = await response.json(); setSummary(data.summary); };
  useEffect(() => { let active = true; request().catch(() => { if (active) setError('History is unavailable right now.'); }); return () => { active = false; }; }, [friendId]);
  const refresh = async () => { setBusy(true); setError(''); try { await request(true); } catch { setError('Could not refresh the friend log.'); } finally { setBusy(false); } };
  const share = async () => { setBusy(true); setError(''); try { const supabase = createClient(); const { data: { session } } = await supabase.auth.getSession(); if (!session) throw new Error(); const response = await fetch('/api/rivalry-shares', { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${session.access_token}` }, body: JSON.stringify({ friendId, includeDecks: true }) }); if (!response.ok) throw new Error(); const { shareId: id } = await response.json(); const url = `${window.location.origin}/rivalry/${id}`; setShareId(id); setShared(url); await navigator.clipboard?.writeText(url); } catch { setError('Could not create a share link.'); } finally { setBusy(false); } };
  const revoke = async () => { if (!shareId) return; setBusy(true); try { const supabase = createClient(); const { data: { session } } = await supabase.auth.getSession(); if (!session) throw new Error(); const response = await fetch(`/api/rivalry-shares?shareId=${encodeURIComponent(shareId)}`, { method: 'DELETE', headers: { Authorization: `Bearer ${session.access_token}` } }); if (!response.ok) throw new Error(); setShared(''); setShareId(''); } catch { setError('Could not revoke the share link.'); } finally { setBusy(false); } };
  return <section className="mt-4 rounded-lg border border-blue-100 bg-blue-50 p-4" aria-label={`Insights for ${friendName}`}>
    <div className="flex flex-wrap items-center justify-between gap-2"><div><h4 className="font-semibold text-gray-900">Recent deck habits</h4><p className="text-xs text-gray-500">{friendTag}</p></div><div className="flex flex-wrap gap-2"><button onClick={refresh} disabled={busy} className="rounded border border-blue-200 bg-white px-3 py-1.5 text-xs font-semibold text-blue-700">{busy ? 'Working…' : 'Refresh history'}</button><button onClick={() => router.push(`/counter-deck?friendId=${encodeURIComponent(friendId)}`)} className="rounded bg-blue-600 px-3 py-1.5 text-xs font-semibold text-white">Build a counter</button><button onClick={share} disabled={busy} className="rounded border border-blue-200 bg-white px-3 py-1.5 text-xs font-semibold text-blue-700">Share rivalry</button>{shareId && <button onClick={revoke} disabled={busy} className="rounded border border-red-200 bg-white px-3 py-1.5 text-xs font-semibold text-red-700">Revoke link</button>}</div></div>
    {summary && <><p className="mt-3 text-sm text-gray-700">{summary.recordedMatches} recorded eligible matches · top 3 cover {Math.round(summary.coverage * 100)}%</p><div className="mt-2 space-y-2">{summary.topDecks.map((deck, i) => <button key={deck.key} onClick={() => router.push(`/counter-deck?friendId=${encodeURIComponent(friendId)}&deck=${encodeURIComponent(deck.key)}`)} className="block w-full rounded bg-white p-2 text-left text-xs text-gray-700 hover:bg-blue-100"><span className="font-semibold">Deck {i + 1}</span> · {deck.count} matches ({Math.round(deck.share * 100)}%) · {deck.cards.map(card => card.name || card.id).join(', ')}</button>)}</div></>}
    {error && <p className="mt-2 text-xs text-red-600">{error}</p>}{shared && <p className="mt-2 break-all text-xs text-green-700">Link copied: {shared}</p>}
  </section>;
}
