'use strict';
const $=id=>document.getElementById(id), esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let lockedKeys=new Set(), counterBusy=false, counterRevision=0;
let catalog, examples, metrics, lookup, decks, selection={side:0,slot:0}, prediction=null, selectedStage=0, revision=0;
const formName=c=>c.form===1?'Evolution':c.form===2?'Hero':c.champion?'Champion':'Base';
const stages=[
 ['01','Embeddings','2 × 9 × 64','Each base/form pair has its own learned embedding. The model adds level and elixir features, plus a separate tower token. The bars show eight of the first card’s 64 actual embedding activations.'],
 ['02','Self-attention','2 shared layers','Each card consults the other cards in its own deck. Four attention heads mix information in parallel; residual connections and feedforward layers update the representations. Both decks use the same weights.'],
 ['03','Cross-attention','4 heads · 9 × 9','Cards in deck A query cards in deck B, and vice versa. The heatmap below shows the actual normalized weights for this matchup. This is information routing, not a claim that the brightest square is the strongest counter.'],
 ['04','Pool & score','64 → 128 → 64 → 1','The model averages the nine updated tokens for each deck. A small feedforward network scores both orderings of the pooled deck representations.'],
 ['05','Probability','sigmoid((gAB − gBA) / T)','Subtracting the reverse score makes swapping the decks complement the probability. A temperature fitted only on the calibration window adjusts confidence before the sigmoid produces the final estimate.']
];
async function api(path,body){const r=await fetch(path,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:undefined);const data=await r.json();if(!r.ok)throw Error(data.error||'Request failed');return data;}
function route(){const name=['arena','model','results'].includes(location.hash.slice(1))?location.hash.slice(1):'arena';document.querySelectorAll('.page').forEach(e=>e.hidden=e.id!==name);document.querySelectorAll('nav a').forEach(a=>{const active=a.dataset.page===name;a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});$('crumb').textContent={arena:'MATCHUP ARENA',model:'INSIDE THE MODEL',results:'EVALUATION'}[name];if(name==='results'&&metrics)charts();}
function blankDeck(){return{cards:Array(8).fill(null),tower_id:catalog.towers[0].id,tower_level:16};}
function invalidate(){revision++;counterRevision++;$('attention-network').replaceChildren();$('counter-results').replaceChildren();$('counter-status').textContent='';renderLocks();prediction=null;$('prediction-ready').hidden=true;$('prediction-empty').hidden=false;$('prediction-status').textContent='';$('warnings').replaceChildren();$('heatmap-wrap').hidden=true;$('attention-empty').hidden=false;$('embedding-preview').replaceChildren();$('predict').disabled=!decks.every(d=>d.cards.every(Boolean));}
function renderDecks(){
 $('decks').innerHTML=decks.map((deck,side)=>{
 const cs=deck.cards.filter(Boolean).map(c=>lookup[c.key]);const costs=cs.filter(c=>c.elixir!==null);const avg=costs.length?costs.reduce((s,c)=>s+c.elixir,0)/costs.length:0;const mirror=cs.some(c=>c.card_id===28000006);
 return `<article class="deck panel ${side?'b':''}"><div class="deck-top"><div class="deck-title"><span class="deck-letter">${'AB'[side]}</span><h2>Deck ${'AB'[side]}</h2></div><span class="deck-count">${cs.length} / 8 cards</span></div><div class="slots">${deck.cards.map((entry,slot)=>{const c=entry?lookup[entry.key]:null;return `<div class="slot"><button class="slot-button ${c?'filled':''}" data-side="${side}" data-slot="${slot}" aria-label="Deck ${'AB'[side]}, slot ${slot+1}: ${c?esc(c.name):'choose a card'}"><span class="slot-number">${slot+1}</span>${c?`<img src="${esc(c.image)}" alt="" width="80" height="80"><span class="slot-name">${esc(c.base_name)}</span><span class="slot-kind ${c.form===2?'hero':''}">${formName(c)}</span>`:'<span class="plus">+</span><span class="slot-name">Add card</span>'}</button>${c?`<select data-level-side="${side}" data-level-slot="${slot}" aria-label="Level of ${esc(c.name)} in deck ${'AB'[side]}">${Array.from({length:17-c.min_level},(_,i)=>c.min_level+i).map(l=>`<option ${l===entry.level?'selected':''}>${l}</option>`).join('')}</select>`:''}</div>`;}).join('')}</div><div class="tower-row"><label>Tower troop<select data-tower="${side}">${catalog.towers.map(t=>`<option value="${t.id}" ${t.id===deck.tower_id?'selected':''}>${esc(t.name)}</option>`).join('')}</select></label><label>Level<select data-tower-level="${side}">${Array.from({length:16},(_,i)=>i+1).map(l=>`<option ${l===deck.tower_level?'selected':''}>${l}</option>`).join('')}</select></label></div><div class="deck-info"><span>${avg?avg.toFixed(1):'—'} avg elixir${mirror?'*':''}</span><span>${cs.filter(c=>c.form>0||c.champion).length} special slots</span></div>${mirror?'<p class="fine">*Average excludes variable-cost Mirror.</p>':''}</article>`;
 }).join('');
 $('decks').querySelectorAll('[data-slot]').forEach(b=>b.onclick=()=>openPicker(+b.dataset.side,+b.dataset.slot));
 $('decks').querySelectorAll('[data-level-side]').forEach(el=>el.onchange=()=>{decks[+el.dataset.levelSide].cards[+el.dataset.levelSlot].level=+el.value;invalidate();});
 $('decks').querySelectorAll('[data-tower]').forEach(el=>el.onchange=()=>{decks[+el.dataset.tower].tower_id=+el.value;invalidate();});
 $('decks').querySelectorAll('[data-tower-level]').forEach(el=>el.onchange=()=>{decks[+el.dataset.towerLevel].tower_level=+el.value;invalidate();});
 $('predict').disabled=!decks.every(d=>d.cards.every(Boolean));
}
function renderLocks(){
 if(!decks)return;const current=decks[0].cards.filter(Boolean);lockedKeys=new Set([...lockedKeys].filter(k=>current.some(c=>c.key===k)));
 $('counter-locks').innerHTML=current.length?current.map(c=>`<label><input type="checkbox" data-lock="${esc(c.key)}" ${lockedKeys.has(c.key)?'checked':''}>Lock ${esc(lookup[c.key].name)}</label>`).join(''):'<span class="muted">Add cards to Deck A to lock part of the result.</span>';
 $('counter-locks').querySelectorAll('input').forEach(el=>el.onchange=()=>{el.checked?lockedKeys.add(el.dataset.lock):lockedKeys.delete(el.dataset.lock);counterRevision++;$('counter-results').replaceChildren();});
 $('find-counter').disabled=counterBusy||!decks[1].cards.every(Boolean);
}
async function findCounter(){
 const version=counterRevision;counterBusy=true;renderLocks();$('counter-results').replaceChildren();$('counter-status').textContent='Exploring legal decks...';
 try{
 const result=await api('/api/counter',{target:decks[1],locked:[...lockedKeys],level:+$('counter-level').value,tower_id:decks[0].tower_id,tower_level:decks[0].tower_level,min_elixir:+$('min-elixir').value,max_elixir:+$('max-elixir').value});
 if(version!==counterRevision){$('counter-status').textContent='Decks or constraints changed during search. Search again for current settings.';return;}
 $('counter-status').textContent=`Compared ${result.evaluated.toLocaleString()} legal candidates. Ranked by model score with a fixed preference for fewer changes from observed decks.`;
 $('counter-results').innerHTML=result.candidates.map((c,i)=>`<article class="counter-card"><div class="panel-title"><h3>Candidate ${i+1}</h3><strong>${(c.probability*100).toFixed(1)}% <small>model estimate</small></strong></div><div class="counter-cards">${c.keys.map(k=>`<div><img src="${esc(lookup[k].image)}" alt="" width="52" height="60"><span>${esc(lookup[k].name)}</span></div>`).join('')}</div><p>${c.changes} changes from an observed training deck; ${c.training_deck_appearances} exact deck appearances in the seed library</p><button class="quiet" data-apply-counter="${i}">Use in Deck A</button></article>`).join('');
 $('counter-results').querySelectorAll('[data-apply-counter]').forEach(el=>el.onclick=()=>{decks[0]=structuredClone(result.candidates[+el.dataset.applyCounter].deck);invalidate();renderDecks();analyze();});
 }catch(e){$('counter-status').textContent=e.message;}finally{counterBusy=false;renderLocks();}
}
function openPicker(side,slot){selection={side,slot};$('picker-target').textContent=`DECK ${'AB'[side]} · SLOT ${slot+1}`;$('search').value='';$('form-filter').value='all';library();$('picker').showModal();$('search').focus();}
function library(){const query=$('search').value.toLowerCase().trim(),form=$('form-filter').value;const chosen=new Set(decks[selection.side].cards.filter((c,i)=>c&&i!==selection.slot).map(c=>lookup[c.key].card_id));const cards=catalog.variants.filter(c=>c.name.toLowerCase().includes(query)&&(form==='all'||(form==='champion'?c.champion:String(c.form)===form)));$('picker-count').textContent=`${cards.length} card forms · ${catalog.base_card_count} base cards in this catalog`;
 $('card-library').innerHTML=cards.map(c=>`<button class="library-card" data-key="${c.key}" ${chosen.has(c.card_id)||!c.train_occurrences?'disabled':''}><img src="${esc(c.image)}" alt="" width="76" height="90" loading="lazy"><strong>${esc(c.name)}</strong><small>${c.elixir===null?'Variable':c.elixir} elixir · ${formName(c)}</small><small>${chosen.has(c.card_id)?'Already in this deck':c.train_occurrences.toLocaleString()+' train appearances'}</small></button>`).join('');
 $('card-library').querySelectorAll('button').forEach(b=>b.onclick=()=>{decks[selection.side].cards[selection.slot]={key:b.dataset.key,level:16};$('picker').close();invalidate();renderDecks();});
}
async function analyze(){const thisRevision=revision;$('predict').disabled=true;$('prediction-status').textContent='Running the trained network…';try{const data=await api('/api/predict',{decks});if(thisRevision!==revision)return;prediction=data;$('prediction-empty').hidden=true;$('prediction-ready').hidden=false;$('probability').textContent=(data.probability_a*100).toFixed(1);$('prob-fill').style.width=`${data.probability_a*100}%`;$('pa').textContent=`A ${(data.probability_a*100).toFixed(1)}%`;$('pb').textContent=`B ${(data.probability_b*100).toFixed(1)}%`;const margin=Math.abs(data.probability_a-.5);$('edge').textContent=margin<.025?'Close to even. The model sees little separation.':`The model leans toward deck ${data.probability_a>.5?'A':'B'}. Execution can easily change the outcome.`;$('prediction-status').textContent='';$('warnings').innerHTML=data.warnings.map(w=>`<p>${esc(w)}</p>`).join('');heatmap();stage(selectedStage);}catch(e){$('prediction-status').textContent=e.message;}finally{if(thisRevision===revision)$('predict').disabled=!decks.every(d=>d.cards.every(Boolean));}}
function stage(index){selectedStage=index;$('pipeline').innerHTML=stages.map((s,i)=>`<button class="stage ${i===index?'active':''}" data-stage="${i}" aria-pressed="${i===index}"><span>${s[0]}</span><strong>${s[1]}</strong><small>${s[2]}</small></button>`).join('');$('pipeline').querySelectorAll('button').forEach(b=>b.onclick=()=>stage(+b.dataset.stage));$('stage-detail').textContent=stages[index][3];$('embedding-preview').replaceChildren();if(prediction&&(index===0||index===3)){const values=index===0?prediction.trace.embeddings[0][0]:prediction.trace.pooled[0];const max=Math.max(...values.map(Math.abs),.01);$('embedding-preview').innerHTML=values.map(v=>`<div style="height:${10+Math.abs(v)/max*40}px;opacity:${v>=0?1:.35}" title="${v.toFixed(3)}"></div>`).join('')+`<span>8 of 64 actual activations<br>${index===0?esc(prediction.token_names[0][0]):'Deck A pooled representation'} · negative values are dimmed</span>`;}}
function connectionGraph(query,names,weights){
const svg=$('attention-network'),w=Math.max(280,svg.parentElement.clientWidth-48),x=w-130;
svg.setAttribute('viewBox',`0 0 ${w} 340`);
svg.innerHTML=weights.map((v,i)=>`<line x1="45" y1="170" x2="${x}" y2="${25+i*35}" stroke="#74e7d2" stroke-opacity="${.2+v*.8}" stroke-width="${1+v*18}"/>`).join('')+`<circle cx="45" cy="170" r="14" fill="#74e7d2"/><text x="8" y="205" fill="#dae6ed" font-size="10">${esc(query)}</text>`+names.map((n,i)=>`<circle cx="${x}" cy="${25+i*35}" r="6" fill="#74e7d2"/><text x="${x+12}" y="${29+i*35}" fill="#dae6ed" font-size="10">${esc(n)}</text>`).join('');
}
function heatmap(){if(!prediction)return;$('attention-empty').hidden=true;$('heatmap-wrap').hidden=false;const mode=$('attention-view').value,head=$('head').value;let source,target,heads;if(mode.startsWith('self')){source=target=mode==='self_a'?0:1;heads=prediction.trace.self_attention.at(-1)[source];}else{source=mode==='cross_ab'?0:1;target=1-source;heads=prediction.trace[mode];}const matrix=head==='mean'?heads[0].map((row,i)=>row.map((_,j)=>heads.reduce((s,h)=>s+h[i][j],0)/heads.length)):heads[+head];const names=prediction.token_names;const max=Math.max(...matrix.flat(),.01);$('heatmap').innerHTML='<div></div>'+names[target].map(n=>`<div class="col-label">${esc(n)}</div>`).join('')+matrix.map((row,i)=>`<div class="row-label">${esc(names[source][i])}</div>`+row.map((v,j)=>{const alpha=.08+.75*v/max;return `<button data-row="${i}" data-col="${j}" style="background:rgba(116,231,210,${alpha})" aria-label="${esc(names[source][i])} attends to ${esc(names[target][j])}: ${(v*100).toFixed(1)} percent" title="${(v*100).toFixed(1)}%">${(v*100).toFixed(0)}</button>`;}).join('')).join('');const select=(i,j,button)=>{connectionGraph(names[source][i],names[target],matrix[i]);$('heatmap').querySelectorAll('button').forEach(b=>b.classList.remove('selected'));button.classList.add('selected');$('connection').textContent=`${names[source][i]} → ${names[target][j]}`;$('attention-value').textContent=(matrix[i][j]*100).toFixed(1)+'%';$('connection-copy').textContent=`Of this query token’s attention ${head==='mean'?'averaged across four heads':'in head '+(+head+1)}. This measures information mixing, not win contribution.`;};$('heatmap').querySelectorAll('button').forEach(b=>b.onclick=()=>select(+b.dataset.row,+b.dataset.col,b));const first=$('heatmap').querySelector('button');select(0,0,first);}
function renderMetrics(){const m=metrics.models.attention, t=m.test, counts=metrics.split_counts;$('test-window').textContent=`${t.rows.toLocaleString()} held-out games`;$('metric-cards').innerHTML=[['TEST ACCURACY',(t.accuracy*100).toFixed(2)+'%',`Approx. player-grouped interval ${(t.accuracy_player_cluster_95pct[0]*100).toFixed(1)}–${(t.accuracy_player_cluster_95pct[1]*100).toFixed(1)}%`],['PROBABILITY LOG LOSS',t.log_loss.toFixed(4),'50/50 baseline: 0.6931 · lower is better'],['RANKING QUALITY · AUC',t.auc.toFixed(3),'0.5 is chance · 1.0 is perfect ranking']].map(([label,value,note])=>`<article class="panel"><span class="section-label">${label}</span><div class="metric-value">${value}</div><p>${note}</p></article>`).join('');const labels={attention:'Deck attention · calibrated',card_linear:'Linear card/form baseline',rating_only:'Rating-only baseline',chance:'Constant 50/50',training_prior:'Training class prior'};$('metrics-table').querySelector('tbody').innerHTML=['attention','card_linear','rating_only','chance','training_prior'].map(k=>{const v=metrics.models[k].test;return`<tr class="${k==='attention'?'featured':''}"><td>${labels[k]}</td><td>${(v.accuracy*100).toFixed(2)}%</td><td>${v.log_loss.toFixed(4)}</td><td>${v.brier.toFixed(4)}</td><td>${v.auc.toFixed(3)}</td></tr>`;}).join('');const total=Object.values(counts).reduce((a,b)=>a+b,0);$('split-bar').innerHTML=Object.values(counts).map(n=>`<div style="flex:${n}" title="${n.toLocaleString()} games"></div>`).join('');$('split-details').innerHTML=Object.entries(counts).map(([key,n])=>`<div>${key[0].toUpperCase()+key.slice(1)}<strong>${n.toLocaleString()}</strong>${(n/total*100).toFixed(1)}%</div>`).join('');$('method-details').innerHTML=`<div><b>Architecture</b>${m.parameters.toLocaleString()} trainable parameters · 64-dimensional embeddings · 2 shared self-attention layers · 4 heads · cross-attention · antisymmetric scoring head.</div><div><b>Selection and calibration</b>Best validation epoch ${m.best_epoch} of ${m.history.length}. Temperature ${m.temperature.toFixed(3)} fitted on a separate calibration window. The test set was not used for either choice.</div><div><b>Data and weighting</b>${metrics.data_manifest.snapshot_raw_count.toLocaleString()} unique raw Ranked games → ${total.toLocaleString()} usable matches. Training loss uses a 14-day half-life. Test loss is unweighted.</div><div><b>Chronology</b>Training ends ${esc(metrics.data_manifest.train_cutoff_utc)}. Test begins ${esc(metrics.data_manifest.test_start_utc)}. The short window does not measure resilience to future patches.</div>`;charts();}
function svgPlot(id,series,xDomain,yDomain,xLabel,yLabel,diagonal=false){const svg=$(id);const w=Math.max(svg.parentElement.clientWidth-48,270),h=255,p={l:48,r:20,t:18,b:42};svg.setAttribute('viewBox',`0 0 ${w} ${h}`);const x=v=>p.l+(v-xDomain[0])/(xDomain[1]-xDomain[0])*(w-p.l-p.r),y=v=>h-p.b-(v-yDomain[0])/(yDomain[1]-yDomain[0])*(h-p.t-p.b);let markup='';for(let i=0;i<=4;i++){const v=yDomain[0]+(yDomain[1]-yDomain[0])*i/4;markup+=`<line class="grid" x1="${p.l}" x2="${w-p.r}" y1="${y(v)}" y2="${y(v)}"/><text x="${p.l-7}" y="${y(v)+3}" text-anchor="end">${v.toFixed(diagonal?2:3)}</text>`;const xv=xDomain[0]+(xDomain[1]-xDomain[0])*i/4;markup+=`<text x="${x(xv)}" y="${h-p.b+18}" text-anchor="middle">${xv.toFixed(diagonal?2:0)}</text>`;}if(diagonal)markup+=`<path d="M${x(0)} ${y(0)} L${x(1)} ${y(1)}" fill="none" stroke="#536278" stroke-dasharray="4 4"/>`;for(const s of series){markup+=`<path d="${s.data.map((d,i)=>`${i?'L':'M'}${x(d.x)} ${y(d.y)}`).join(' ')}" fill="none" stroke="${s.color}" stroke-width="2"/>`+s.data.map(d=>`<circle cx="${x(d.x)}" cy="${y(d.y)}" r="${diagonal?4:3}" fill="${s.color}"><title>${esc(d.label||`x ${d.x}: ${d.y.toFixed(4)}`)}</title></circle>`).join('');}markup+=`<text x="${(w+p.l-p.r)/2}" y="${h-3}" text-anchor="middle">${xLabel}</text><text transform="translate(12 ${(h-p.b+p.t)/2}) rotate(-90)" text-anchor="middle">${yLabel}</text>`;svg.innerHTML=markup;}
function charts(){if(!metrics||$('results').hidden)return;const history=metrics.models.attention.history;const vals=history.flatMap(h=>[h.train_weighted_log_loss,h.validation_log_loss]);svgPlot('loss-chart',[{color:'#74e7d2',data:history.map(h=>({x:h.epoch,y:h.train_weighted_log_loss}))},{color:'#f1c47c',data:history.map(h=>({x:h.epoch,y:h.validation_log_loss}))}],[1,Math.max(2,history.length)],[Math.min(...vals)-.003,Math.max(...vals)+.003],'Epoch','Log loss');svgPlot('calibration-chart',[{color:'#74e7d2',data:metrics.models.attention.test.calibration_bins.map(b=>({x:b.predicted,y:b.observed,label:`${b.count} games: ${(100*b.predicted).toFixed(1)}% predicted, ${(100*b.observed).toFixed(1)}% observed`}))}],[0,1],[0,1],'Predicted win probability','Observed win fraction',true);}
async function init(){try{[catalog,examples,metrics]=await Promise.all([api('/api/catalog'),api('/api/examples'),api('/api/metrics')]);lookup=Object.fromEntries(catalog.variants.map(c=>[c.key,c]));decks=structuredClone(examples[0].decks);$('example').innerHTML+=examples.map((e,i)=>`<option value="${i}">${esc(e.name)}</option>`).join('');$('example').value='0';$('example').onchange=()=>{if($('example').value==='')return;decks=structuredClone(examples[+$('example').value].decks);invalidate();renderDecks();};$('clear').onclick=()=>{decks=[blankDeck(),blankDeck()];$('example').value='';invalidate();renderDecks();};$('close-picker').onclick=()=>$('picker').close();$('picker').addEventListener('click',e=>{if(e.target===$('picker')){const r=$('picker').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('picker').close();}});$('search').oninput=library;$('form-filter').onchange=library;$('predict').onclick=analyze;$('attention-view').onchange=heatmap;$('head').onchange=heatmap;$('find-counter').onclick=findCounter;['counter-level','min-elixir','max-elixir'].forEach(id=>$(id).onchange=()=>{counterRevision++;$('counter-results').replaceChildren();});renderDecks();renderLocks();stage(0);route();renderMetrics();renderCohorts();await analyze();}catch(e){$('prediction-status').textContent='Could not load the experiment: '+e.message;}}
window.addEventListener('hashchange',route);window.addEventListener('resize',()=>charts());init();

async function renderCohorts(){
 const results=metrics.models.attention.test.test_by_league;if(!results)return;
 document.querySelector('.sidebar>.section-label').textContent='EXPANDED EXPERIMENT';document.querySelector('.topbar .pill').textContent='Attention model · expanded';document.querySelector('.sidebar-bottom p').innerHTML='Standard Ranked 1v1<br>Grand / Royal / Ultimate';document.querySelector('.prediction>.fine').textContent='Experimental model estimate. Recent Grand, Royal and Ultimate Champion games; unfamiliar decks may generalize poorly.';
 const caveat=document.querySelector('.caveat p');caveat.textContent='The model predicts recent Ranked outcomes across Grand, Royal and Ultimate Champion. It cannot see execution, starting hand or familiarity. New patches and unusual decks remain unvalidated. This is an experimental recommendation tool.';
 let html='<h2>Performance by league</h2><div class="table-scroll"><table><thead><tr><th>League</th><th>Test games</th><th>Accuracy</th><th>Log loss</th></tr></thead><tbody>'+Object.entries(results).map(([k,r])=>`<tr><td>${({5:'Grand Champion',6:'Royal Champion',7:'Ultimate Champion'})[k]}</td><td>${r.rows.toLocaleString()}</td><td>${(r.accuracy*100).toFixed(2)}%</td><td>${r.log_loss.toFixed(4)}</td></tr>`).join('')+'</tbody></table></div>';
 const panel=document.createElement('div');panel.className='panel';panel.innerHTML=html;$('results').appendChild(panel);
}
