import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Model Methodology',
  description: 'How Rival Royale estimates Clash Royale deck matchups and searches for supported candidates.',
  alternates: { canonical: '/models' },
};

export default function ModelsPage() {
  return <main className="min-h-[calc(100vh-73px)] bg-[#0d1024] px-4 py-12 text-slate-100 sm:px-6 lg:px-8"><article className="mx-auto max-w-4xl"><span className="inline-flex rounded-full border border-violet-300/20 bg-violet-300/10 px-3 py-1 text-xs font-semibold uppercase tracking-[0.18em] text-violet-200">Rival Royale · methodology</span><h1 className="mt-5 text-4xl font-black tracking-tight text-white sm:text-6xl">A useful estimate, with the limits visible.</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-slate-300">Rival Royale scores complete eight-card decks against one another using a frozen, calibrated attention model trained on recorded Ranked-style matches. The output is a model-estimated matchup advantage, not a promise of what any individual player will win.</p><div className="mt-10 grid gap-5 sm:grid-cols-2"><section className="rounded-3xl border border-white/10 bg-slate-950/60 p-6"><h2 className="text-xl font-bold text-white">What goes into a score</h2><p className="mt-3 text-sm leading-6 text-slate-400">Card identity, Evolution or Hero form, card level, tower troop, and tower level. Deck order does not matter. The service validates eight distinct base cards and supported special-slot combinations before scoring.</p></section><section className="rounded-3xl border border-white/10 bg-slate-950/60 p-6"><h2 className="text-xl font-bold text-white">How search works</h2><p className="mt-3 text-sm leading-6 text-slate-400">Counter search starts from observed decks and explores legal card replacements within a fixed search budget. Each complete deck is scored against the target or a frequency-weighted basket of historical decks. It returns the best supported candidates within that search budget, not a globally optimal answer.</p></section><section className="rounded-3xl border border-white/10 bg-slate-950/60 p-6"><h2 className="text-xl font-bold text-white">Read the percentage carefully</h2><p className="mt-3 text-sm leading-6 text-slate-400">The percentage is conditional on the model’s training coverage and a decisive match. Rare cards, new balance changes, unusual combinations, and player skill can make the estimate less reliable. Support warnings are retained in service responses.</p></section><section className="rounded-3xl border border-white/10 bg-slate-950/60 p-6"><h2 className="text-xl font-bold text-white">Why this is a beta</h2><p className="mt-3 text-sm leading-6 text-slate-400">The current model is a research-backed baseline. The two-layer attention model achieved 57.77% accuracy on 48,638 held-out matches. Future releases still need checks for calibration, rare decks, and drift after balance changes.</p></section></div><p className="mt-8 text-sm leading-6 text-slate-500">The model does not observe your in-game decisions, opponent skill, placement, or starting-hand sequence. Use the tools to compare ideas and make informed deck choices.</p></article></main>;
}
